name: Deploy Docker image

on:
  workflow_run:
    workflows: ["Publish Docker image"]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy:
    needs: docker-publish.build-and-push-image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASSPHRASE }}
          script: |
            docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}
            docker run -d -p 443:443                      \
              -e SSL_PASSWORD=${{ secrets.SSL_PASSWORD }} \
              -e ADMIN_NAME=${{ secrets.ADMIN_NAME }}     \
              -e ADMIN_PSWD=${{ secrets.ADMIN_PSWD }}     \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }}   \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }}   \
              -e USER_NAME=${{ secrets.USER_NAME }}       \
              -e USER_PSWD=${{ secrets.USER_PSWD }}       \
              ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tags }}